### ISSUE TITLE
filter out all items with an item id under 185000

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/SaddlebagExchangeWoW#15]
So our db only has data for dragonflight items atm and we dont add anything in under an item id of 185000, we should make sure for now that something like this doesnt pop up and that there are warnings and error messages telling people we only do dragonfight atm

should be a simple if statement rejecting ids under 185000 and then when we go back to supporting all data we can undo it

```
{
    "homeRealmName": "Ragnaros",
    "region": "EU",
    "user_auctions": [
        {"itemID": 159205,"price": 42500700},
        {"itemID": 177807,"price": 48916800},
        {"itemID": 20906,"price": 209700},
        {"itemID": 20815,"price": 4858200}
    ]
}
```

**Comment by void7604** [comment]
So, as I understand it, we only need to export item IDs that are introduced in dragonflight ?

**Comment by void7604** [comment]
``local _, _, _, _, _, _, _, itemStackCount,_,_,_,_,_,_,expacID= GetItemInfo(item["itemKey"]["itemID"])
                if itemStackCount == 1 and expacID == 9 then ``
This should do it , using  GetItemInfo() I defined a variable expacID that gives when the item was introduced.
